#!/usr/bin/env node

/**
 * Internal Sites Platform -- Setup Script
 *
 * Runs during the "build" phase of Deploy to Cloudflare.
 *
 * What it does:
 *   1. Creates the dispatch namespace via `wrangler dispatch-namespace create`
 *   2. Validates that DISPATCH_NAMESPACE_API_TOKEN is set
 *   3. Writes ACCOUNT_ID to wrangler config if available from environment
 *
 * What it does NOT do:
 *   - Auto-create API tokens. Users must create their own token with
 *     Account > Workers Scripts > Edit permission.
 */

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const PROJECT_ROOT = path.join(__dirname, "..");

// ── Colors ───────────────────────────────────────────────────────────────────

const green = "\x1b[32m";
const yellow = "\x1b[33m";
const blue = "\x1b[34m";
const cyan = "\x1b[36m";
const red = "\x1b[31m";
const reset = "\x1b[0m";

function log(color, msg) {
	console.log(`${color}${msg}${reset}`);
}

// ── Config readers ───────────────────────────────────────────────────────────

function getDispatchNamespaceFromConfig() {
	const configPath = path.join(PROJECT_ROOT, "wrangler.jsonc");

	if (!fs.existsSync(configPath)) {
		return "internal-sites";
	}

	const content = fs.readFileSync(configPath, "utf-8");
	const match = content.match(/"namespace"\s*:\s*"([^"]+)"/);
	if (match) return match[1];

	const varMatch = content.match(/"DISPATCH_NAMESPACE_NAME"\s*:\s*"([^"]+)"/);
	if (varMatch) return varMatch[1];

	return "internal-sites";
}

function getAccountId() {
	return (
		process.env.CF_ACCOUNT_ID ||
		process.env.CLOUDFLARE_ACCOUNT_ID ||
		process.env.ACCOUNT_ID ||
		null
	);
}

function getDispatchToken() {
	return process.env.DISPATCH_NAMESPACE_API_TOKEN || null;
}

// ── Dispatch namespace ───────────────────────────────────────────────────────

function ensureDispatchNamespace(namespaceName) {
	log(blue, `Creating dispatch namespace '${namespaceName}'...`);

	try {
		execSync(`npx wrangler dispatch-namespace create ${namespaceName}`, {
			stdio: "pipe",
		});
		log(green, `  Dispatch namespace '${namespaceName}' created.`);
		return true;
	} catch (error) {
		const output = error.stdout?.toString() || error.stderr?.toString() || "";

		if (
			output.includes("already exists") ||
			output.includes("A namespace with this name")
		) {
			log(green, `  Dispatch namespace '${namespaceName}' already exists.`);
			return true;
		}

		if (output.includes("You do not have access")) {
			log(
				yellow,
				"  Workers for Platforms is not available on this account.",
			);
			log(
				yellow,
				"  Enable it at: https://dash.cloudflare.com/?to=/:account/workers-for-platforms",
			);
			return false;
		}

		log(
			yellow,
			`  Could not create dispatch namespace: ${output || error.message}`,
		);
		log(yellow, "  Continuing -- you can create it manually.");
		return false;
	}
}

// ── Config update ────────────────────────────────────────────────────────────

function updateWranglerConfig(accountId) {
	if (!accountId) return;

	const configPath = path.join(PROJECT_ROOT, "wrangler.jsonc");
	if (!fs.existsSync(configPath)) return;

	let content = fs.readFileSync(configPath, "utf-8");

	// Check if vars section already has ACCOUNT_ID
	if (content.includes('"ACCOUNT_ID"')) {
		return;
	}

	// Add ACCOUNT_ID to the vars section
	const varsMatch = content.match(/"DISABLE_ACCESS_IDENTITY_CHECK"\s*:\s*"[^"]*"/);
	if (varsMatch) {
		content = content.replace(
			varsMatch[0],
			`${varsMatch[0]},\n\t\t// Cloudflare account ID (auto-set by setup script)\n\t\t"ACCOUNT_ID": "${accountId}"`,
		);
		fs.writeFileSync(configPath, content, "utf-8");
		log(green, "  ACCOUNT_ID added to wrangler.jsonc.");
	}
}

function writeDevVars(accountId, dispatchToken) {
	const devVarsPath = path.join(PROJECT_ROOT, ".dev.vars");

	// Don't overwrite existing .dev.vars
	if (fs.existsSync(devVarsPath)) {
		log(cyan, "  .dev.vars already exists -- skipping.");
		return;
	}

	const lines = ["# Auto-generated by setup script"];

	if (dispatchToken) {
		lines.push(`DISPATCH_NAMESPACE_API_TOKEN="${dispatchToken}"`);
	}

	if (accountId) {
		lines.push(`ACCOUNT_ID="${accountId}"`);
	}

	if (lines.length > 1) {
		fs.writeFileSync(devVarsPath, lines.join("\n") + "\n", "utf-8");
		log(green, "  .dev.vars file created.");
	}
}

// ── Main ─────────────────────────────────────────────────────────────────────

function main() {
	console.log("");
	log(blue, "Internal Sites Platform -- Setup");
	log(blue, "────────────────────────────────");
	console.log("");

	const accountId = getAccountId();
	const dispatchToken = getDispatchToken();
	const namespaceName = getDispatchNamespaceFromConfig();

	// Show status
	log(cyan, "  Configuration:");
	log(cyan, `    Account ID: ${accountId ? accountId.substring(0, 8) + "..." : "(not found)"}`);
	log(cyan, `    Dispatch token: ${dispatchToken ? "set" : "(not set)"}`);
	log(cyan, `    Namespace: ${namespaceName}`);
	console.log("");

	// 1. Create dispatch namespace
	ensureDispatchNamespace(namespaceName);
	console.log("");

	// 2. Validate token
	if (!dispatchToken) {
		log(yellow, "  DISPATCH_NAMESPACE_API_TOKEN is not set.");
		log(yellow, "");
		log(yellow, "  You need an API token to deploy sites into the dispatch namespace.");
		log(yellow, "  Create one at: https://dash.cloudflare.com/profile/api-tokens");
		log(yellow, "");
		log(yellow, "  Use 'Create Custom Token' with:");
		log(yellow, "    Account > Workers Scripts > Edit");
		log(yellow, "");
		log(yellow, "  Then set it as a secret:");
		log(yellow, "    npx wrangler secret put DISPATCH_NAMESPACE_API_TOKEN");
		console.log("");
	} else {
		log(green, "  DISPATCH_NAMESPACE_API_TOKEN is set.");
	}

	// 3. Update config with account ID
	updateWranglerConfig(accountId);

	// 4. Write .dev.vars if in deploy flow
	writeDevVars(accountId, dispatchToken);

	console.log("");
	log(green, "  Setup complete.");
	console.log("");
	log(blue, "  Next steps:");
	log(blue, "    1. Deploy: npx wrangler deploy");
	log(blue, "    2. Configure Cloudflare Access (see README)");
	log(blue, "    3. Attach your domain and add wildcard DNS (see README)");
	console.log("");
}

main();
