#!/usr/bin/env node

/**
 * Internal Sites Platform -- Setup Script
 *
 * Runs during the "build" phase of Deploy to Cloudflare.
 *
 * What it does:
 *   1. Creates the dispatch namespace via `wrangler dispatch-namespace create`
 *   2. Writes ACCOUNT_ID and DISPATCH_NAMESPACE_API_TOKEN to .dev.vars
 *   3. On --set-secrets flag: sets secrets via `wrangler secret put`
 *
 * What it does NOT do:
 *   - Auto-create API tokens. Users must create their own token with
 *     Account > Workers Scripts > Edit permission.
 *   - Modify wrangler.jsonc. The config stays clean for the deploy flow.
 */

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const PROJECT_ROOT = path.join(__dirname, "..");

// ── Colors ───────────────────────────────────────────────────────────────────

const green = "\x1b[32m";
const yellow = "\x1b[33m";
const blue = "\x1b[34m";
const cyan = "\x1b[36m";
const reset = "\x1b[0m";

function log(color, msg) {
	console.log(`${color}${msg}${reset}`);
}

// ── Config readers ───────────────────────────────────────────────────────────

function getDispatchNamespaceFromConfig() {
	const configPath = path.join(PROJECT_ROOT, "wrangler.jsonc");

	if (!fs.existsSync(configPath)) {
		return "internal-sites";
	}

	const content = fs.readFileSync(configPath, "utf-8");
	const match = content.match(/"namespace"\s*:\s*"([^"]+)"/);
	if (match) return match[1];

	return "internal-sites";
}

function getAccountId() {
	return (
		process.env.CF_ACCOUNT_ID ||
		process.env.CLOUDFLARE_ACCOUNT_ID ||
		process.env.ACCOUNT_ID ||
		null
	);
}

function getDispatchToken() {
	return process.env.DISPATCH_NAMESPACE_API_TOKEN || null;
}

// ── Dispatch namespace ───────────────────────────────────────────────────────

function ensureDispatchNamespace(namespaceName) {
	log(blue, `Creating dispatch namespace '${namespaceName}'...`);

	try {
		execSync(`npx wrangler dispatch-namespace create ${namespaceName}`, {
			stdio: "pipe",
		});
		log(green, `  Dispatch namespace '${namespaceName}' created.`);
		return true;
	} catch (error) {
		const output = error.stdout?.toString() || error.stderr?.toString() || "";

		if (
			output.includes("already exists") ||
			output.includes("A namespace with this name")
		) {
			log(green, `  Dispatch namespace '${namespaceName}' already exists.`);
			return true;
		}

		if (output.includes("You do not have access")) {
			log(
				yellow,
				"  Workers for Platforms is not available on this account.",
			);
			log(
				yellow,
				"  Enable it at: https://dash.cloudflare.com/?to=/:account/workers-for-platforms",
			);
			return false;
		}

		log(
			yellow,
			`  Could not create dispatch namespace: ${output || error.message}`,
		);
		log(yellow, "  Continuing -- you can create it manually.");
		return false;
	}
}

// ── .dev.vars ────────────────────────────────────────────────────────────────

function writeDevVars(accountId, dispatchToken) {
	const devVarsPath = path.join(PROJECT_ROOT, ".dev.vars");

	// Read existing .dev.vars if present
	let existing = {};
	if (fs.existsSync(devVarsPath)) {
		const content = fs.readFileSync(devVarsPath, "utf-8");
		for (const line of content.split("\n")) {
			const match = line.match(/^([A-Z_]+)="?([^"]*)"?$/);
			if (match) existing[match[1]] = match[2];
		}
	}

	// Merge: env vars override existing, existing fills gaps
	const vars = {};
	if (dispatchToken) vars.DISPATCH_NAMESPACE_API_TOKEN = dispatchToken;
	else if (existing.DISPATCH_NAMESPACE_API_TOKEN)
		vars.DISPATCH_NAMESPACE_API_TOKEN =
			existing.DISPATCH_NAMESPACE_API_TOKEN;

	if (accountId) vars.ACCOUNT_ID = accountId;
	else if (existing.ACCOUNT_ID) vars.ACCOUNT_ID = existing.ACCOUNT_ID;

	if (Object.keys(vars).length === 0) {
		return;
	}

	const lines = ["# Auto-generated by setup script"];
	for (const [key, value] of Object.entries(vars)) {
		lines.push(`${key}="${value}"`);
	}

	fs.writeFileSync(devVarsPath, lines.join("\n") + "\n", "utf-8");
	log(green, "  .dev.vars written.");
}

// ── Secrets ──────────────────────────────────────────────────────────────────

function setWranglerSecrets() {
	log(blue, "Setting secrets via wrangler...");

	const devVarsPath = path.join(PROJECT_ROOT, ".dev.vars");
	if (!fs.existsSync(devVarsPath)) {
		log(yellow, "  No .dev.vars found -- skipping secrets.");
		return;
	}

	const content = fs.readFileSync(devVarsPath, "utf-8");
	const getVar = (name) => {
		const match = content.match(new RegExp(`${name}="([^"]*)"`));
		return match ? match[1] : null;
	};

	const dispatchToken = getVar("DISPATCH_NAMESPACE_API_TOKEN");
	if (dispatchToken) {
		try {
			execSync(
				`echo "${dispatchToken}" | npx wrangler secret put DISPATCH_NAMESPACE_API_TOKEN`,
				{ stdio: "pipe", cwd: PROJECT_ROOT },
			);
			log(green, "  Set DISPATCH_NAMESPACE_API_TOKEN secret.");
		} catch (error) {
			log(
				yellow,
				`  Could not set DISPATCH_NAMESPACE_API_TOKEN: ${error.message}`,
			);
		}
	}

	const accountId = getVar("ACCOUNT_ID");
	if (accountId) {
		try {
			execSync(
				`echo "${accountId}" | npx wrangler secret put ACCOUNT_ID`,
				{ stdio: "pipe", cwd: PROJECT_ROOT },
			);
			log(green, "  Set ACCOUNT_ID secret.");
		} catch (error) {
			log(yellow, `  Could not set ACCOUNT_ID: ${error.message}`);
		}
	}
}

// ── Main ─────────────────────────────────────────────────────────────────────

function main() {
	console.log("");
	log(blue, "Internal Sites Platform -- Setup");
	log(blue, "────────────────────────────────");
	console.log("");

	const accountId = getAccountId();
	const dispatchToken = getDispatchToken();
	const namespaceName = getDispatchNamespaceFromConfig();

	log(cyan, "  Configuration:");
	log(
		cyan,
		`    Account ID: ${accountId ? accountId.substring(0, 8) + "..." : "(not found)"}`,
	);
	log(cyan, `    Dispatch token: ${dispatchToken ? "set" : "(not set)"}`);
	log(cyan, `    Namespace: ${namespaceName}`);
	console.log("");

	// 1. Create dispatch namespace
	ensureDispatchNamespace(namespaceName);
	console.log("");

	// 2. Validate token
	if (!dispatchToken) {
		log(yellow, "  DISPATCH_NAMESPACE_API_TOKEN is not set.");
		log(yellow, "");
		log(
			yellow,
			"  You need an API token to deploy sites into the dispatch namespace.",
		);
		log(
			yellow,
			"  Create one at: https://dash.cloudflare.com/profile/api-tokens",
		);
		log(yellow, "");
		log(yellow, "  Use 'Create Custom Token' with:");
		log(yellow, "    Account > Workers Scripts > Edit");
		log(yellow, "");
		log(yellow, "  Then set it as a secret:");
		log(yellow, "    npx wrangler secret put DISPATCH_NAMESPACE_API_TOKEN");
		console.log("");
	} else {
		log(green, "  DISPATCH_NAMESPACE_API_TOKEN is set.");
	}

	// 3. Write .dev.vars (used by wrangler for secrets)
	writeDevVars(accountId, dispatchToken);

	// 4. Set secrets if --set-secrets flag is passed (runs after wrangler deploy)
	if (process.argv.includes("--set-secrets")) {
		console.log("");
		setWranglerSecrets();
	}

	console.log("");
	log(green, "  Setup complete.");
	console.log("");
}

main();
